# Generated by Django 6.0.4 on 2026-04-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='skn25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_attr', models.CharField(db_column='name', default='기본값', max_length=32)),
                ('int_attr', models.IntegerField(db_column='salary', default=0)),
                ('bool_attr', models.BooleanField(db_column='Check', default=False)),
                ('datetime_attr', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
