# Generated by Django 6.0.4 on 2026-04-15 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='skn25',
            table='playdata',
        ),
    ]
