# Generated by Django 6.0.4 on 2026-04-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_model', '0002_alter_skn25_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='학생 이름', max_length=128)),
            ],
        ),
    ]
